export const translateToUzk = (word) => {
    let ready = {
        "Oʻ": "Ў",
        "O'": "Ў",
        "oʻ": "ў",
        "o'": "ў",
        "Gʻ": "Ғ",
        "G'": "Ғ",
        "gʻ": "ғ",
        "g'": "ғ",
        "Sh": "Ш",
        "sh": "ш",
        "Ch": "Ч",
        "ch": "ч",
        "Ng": "Нг",
        "ng": "нг",
        "Ya": 'Я',
        "ya":'я',
        "A": "А",
        "a": "а",
        "B": "Б",
        "b": "б",
        "D": "Д",
        "d": "д",
        "E": "Е",
        "e": "е",
        "F": "Ф",
        "f": "ф",
        "G": "Г",
        "g": "г",
        "H": "Ҳ",
        "h": "ҳ",
        "I": "И",
        "i": "и",
        "J": "Ж",
        "j": "ж",
        "Z": "з",
        "z": "З",
        "K": "К",
        "k": "к",
        "L": "Л",
        "l": "л",
        "M": "М",
        "m": "м",
        "N": "Н",
        "n": "н",
        "O": "О",
        "o": "о",
        "P": "П",
        "p": "п",
        "Q": "Қ",
        "q": "қ",
        "R": "Р",
        "r": "р",
        "S": "С",
        "s": "с",
        "T": "Т",
        "t": "т",
        "U": "У",
        "u": "у",
        "V": "В",
        "v": "в",
        "X": "Х",
        "x": "х",
        "Y": "Й",
        "y": "й",
        "Z": "З",
        "z": "з",
        
    }
    // word = word.split('sh').join('ш').split('Sh').join('Ш').split('ч').join('ch').split('Ч').join('Ch').split('ya').join('я').split('Ya').join('Я')
    let answer = word.slice()
    for (const key in ready) {
        answer = answer.split(key).join(ready[key])
    }
    return answer
}